### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by volodymyr-kushnir** [yaroslav-mironyuk/binary#3]
@yaroslav-mironyuk, привіт. Тут в тебе репозиторій не відповідає вимогам (на мою думку). Але ми можемо його підтягнути. Для того тобі треба буде кілька годин зараз оперативно вбити на вивчення всіх ніштяків. Дай мені знати, якщо готовий. І заодно читни трохи [**лайфхаків**](https://github.com/volodymyr-kushnir/agenda).

**Comment by yaroslav-mironyuk** [comment]
привіт, добре

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk ага, окєй.
Вперед ти робиш [**проект**](https://github.com/yaroslav-mironyuk/binary/projects).
Потім ти складаєш в проекті список завдань, потім конвертуєш їх в [**проблеми**](https://github.com/yaroslav-mironyuk/binary/issues) з допомогою меню картки (тої картки, що в проекті, там є конвертування в проблему) і впроваджуєш по одному. Ось тобі приблизний список завдань для проекту:

* додати **README.md** з описом проекту
* перейменувати **zapovit.txt →zapovit-ua.md** (і так само **-de** та **-it**)
* змерджити всі гілки докупи (шоб всі файли опинились в одній гілці)
* додати посилання на ці файли до **README.md**

Далі буде. Якби якісь питання, то звертайся.
Ну і да, тащи, я вболіваю за тебе, але перевіряти будуть хлопці, які челябінським суровим мужикам фору дають.

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk в проекті колонка "Problems" нічого не каже, бо там всьо буде Problems. краще мати колонки Backlog, Ready, In progress і Done, в яких будуть ті картки, які мають відповідний **статус**. тоді менеджер може краще орієнтуватись, шо заплановано, шо готове до роботи, шо в роботі зараз, і шо виконано.

**Comment by volodymyr-kushnir** [comment]
Приклад проекту https://github.com/volodymyr-kushnir/agenda/projects/1

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir файли, які я зберегаю у гілках як можна перейменувати через гіт шел? спробував так git mv zapovit.txt zapovit.md, але каже що fatal:bad source, хоча для головної гілки такий метод спрацював

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir  або ці файли треба створити на компьютері?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk без поняття, можливо ти гілку не переключив і пробуєш перейменувати файл, якого не існує

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk вони мають бути в твому проекті локально, десь на диску в папці, де в тебе лежить той проект, і їх можна перейменувати в **Windows Explorer**'і. переключаєш гілку, **git** розкатує файл тої гілки, перейменовуєш файл, коммітиш, переключаєш гілку...

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir розбив файли по гілкам та почистив те, що було зайвим - вилив зміни до гіту можеш глянути чи все вірно на цьом кроці?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk в markdown-форматі, щоб перейти на новий рядок треба використовувати або два ентери, або в попередньому рядку в кінці ставити два пробіли і тоді ентер. Дибільно, але це чи не єдина нелогічна річ в них, все решта окей.

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk і **Pull Request** мій прийми заодно

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir не розумію як його редагувати....

спочатку треба мержити а потім редагувати, чи я можу його відредагувати і відправити тобі?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk спочатку тобі треба прийняти Pull Request https://github.com/yaroslav-mironyuk/binary/pull/6, там є кнопка для того.

Після того як воно змерджить зміни, тобі потрібно буде з гілки `master` зробити нову гілку `hotfix/spelling-errors`, наприклад, тоді відредагувати мої помилки, коммітнути, запушити гілку назад на GitHub. і вже тоді на GitHub'і ми зробимо Pull Request і зліпимо ті дві гілки.

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk Ярослав... Завдання створюй в **Projects**, проблеми роби **Issues**, не забувай про то (то має робити менеджер, але ти сам собі сьогодні менеджер проекту).
Тут всьо не просто так, тут всьо накупу і треба встигати.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir наче переписав опис readme.md

**Comment by yaroslav-mironyuk** [comment]
тепер мержити гілки?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk майже, але нє.
Тепер таки спулль це все собі, відкрий собі issue, виправ "Шевченко" на "Шевченка" і тоді коммітни зміни з повідомленням "Fixed #<номер-issue>". І тоді `git push` наверх.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir зробив

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir тепер об'єднувати гілки?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk ммм, якщо ти зрозумів як автоматично закривати проблеми використовуючи **fixed #** в повідомленнях коммітів (як ти щойно зробив в комміті https://github.com/yaroslav-mironyuk/binary/commit/f38d75a6815e12eaf46fb5a33e30dad3c59376f3, який закрив https://github.com/yaroslav-mironyuk/binary/issues/7), то — так, ліпи те все докупи.

Зараз я бачу https://github.com/yaroslav-mironyuk/binary/network, після мерджу має бути лише `master`.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir  я закрив його через гыт хаб, треба було автоматично ? :) добре, зараз буду ще пробувати, дякую

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk нє, це окей. Ти просто вписав **fixed issue #7** замість **fixed #7**. Останнім варіантом воно б закрило само.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir круто! вийшло

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir а можна ще робити щоб пысля закриття воно автоматично міняло гілку в "проджектс", що зайвий раз не заходити та не переміщати?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk колонку в проекті малося на увазі, мабуть.
Нє, так нє, бо проект — це щось зовсім інше.
В проекті як правило створюються "історії", а ти закриваєш "проблему". Одна історія може мати ряд проблем. Тому ти повинен закрити проблеми (вручну чи автоматично при комміті), а потім сам маєш піти до проекту і позначити "історію" як вирішену. Тобто ти переміщуєш її в Done. А закриває картку (архівує, видаляє) менеджер — він вирішує чи все готово чи нє. Можливо він відкине "історію" назад і ти почнеш вирішувати додаткові "проблеми", на які він вкаже.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir зрозумів, тобто гіт ще й для організації робочого процесу можна використовувати

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir а якщо проект закритий - в ньому можуть брати участь дофіга людей?

**Comment by yaroslav-mironyuk** [comment]
з обмеженим доступом

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk ну в них є функціонал, так. І навіть дещо вони автоматизовують, щоб було зручніше, інтегровують розробку з менеджментом. Але більшість команд використовують щось по типу **Trello**.

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk не **eng** в назві файлу, а **en**. Це проблема раз.
Проблема два — додати посилання на файли в **README.md**.

Обидві проблеми одною гілкою, але двома коммітами, по одному на проблему. І змерджити потім.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir зробив, але ссилки як раз проставив коли ти писав коментар

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir знайшов помилку, виправив

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk окей, тоді давай тако:

**окрему гілку зробити обов'язково**
- "Заповіт" → **"Заповіт"**
- (1945 рік) → **(1945 рік)**
- фотографію Тараса додати до репозиторію
- фотографію в README.md
- закоммітити
- залити цю гілку і змерджити з `master`-ом

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk ага, і спробуй коммітити типу **"Photo added (fixed #x)"**, а не просто **"fixed #x"**.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir от фак, після того, як змержив - повидаляло тексти

**Comment by volodymyr-kushnir** [comment]
`git revert b77c044fd1a585a1cd43bff4d33b28f3c9ce6ce6`

**Comment by yaroslav-mironyuk** [comment]
дякую, наче встало, а що то було?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk ти мені скажи, комміт b77c044fd1a585a1cd43bff4d33b28f3c9ce6ce6 називається **remove texts** і видаляє чотири файли. Я не знаю для чого то було зроблено.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir дивно, може випадково сталося

а чого коли я в гіт шелі видляю гілку, то вона у мене на сайті гіт хаба не видаляється?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk бо це твоя гілка, а то ґітхаба. Між ними просто "апстрім-лінк", який їх зв'язує, тобто пояснює **git**'у куди пушити. Уявимо на секунду, шо ми обоє стягнули гілку і працюємо, а ти взяв її хлопнув випадково, а **GitHub** взяв і радісно ше мені її хлопнув (грубе пояснення, насправді все трохи тонше).

Випилюй оці всі стронги і інші теги. В тебе файл в маркдауні, а отже `**жирні слова**` в подвійні зірочки, `*косі слова*` в одинарні зірочки.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir  готово

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk окей. Тепер твій репозиторій просить змінити його опис (той шо **GitHub**-опис), додати теги, можливо десь згадати шо то є завдання на академію, можливо файли перейменувати чи перемістити (наприклад, _assets/shevchenko.jpg_). Загалом дивись як зроблена **volodymyr-kushnir/agenda**. Потім читай ще раз лайфхаки, потім маркдаун. А потім піди випий пива. Ну і да, вот тобі зірка на репозиторій, не знаю чи допоможе, завтра дасться чути.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir завтра будуть відомі результати виконання домашки?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk correctamundo!

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir  дякую за допомогу

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir прислали лист, що завдання перевірено, але я не розумію чи пройшов я далі) посилання,що вказано у листі не працює

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk а що за посилання?

**Comment by yaroslav-mironyuk** [comment]
Ваше домашнє завдання до лекції BSA 17 JS. Lecture 1 - Git було перевірено. Якщо у Вас є питання, пишіть їх у поле для коментарів до лекції: BSA 17 JS. Lecture 1 - Git

http://academy.binary-studio.com/#!/user/hometask/591daff16954646a4d163629

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir наче розібрався де оцінка, дякую

ще в мене виникло питання - можна з гітом працювати замість як локально - на робочому веб сервері?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk редагувати файли онлайн без локального репозиторію? Ну на GitHub'і можна, GitLab на власний сервер поставити можна. Але ж проект то тоді як запустити, кожен раз деплоїти хіба.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir ну наприклад, пхп проект - хтось кодить, хтось провіряє, на локальному це не дуже зручно, то прийдеться всім розгортати сервер на локальній машині, потім заливати зміни собі перевіряти і тд, так якось би на веб сервері це робити, ось цікаво як само це можна реалізувати

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir без серверу гіта, на власному

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir чи як правильно працювати? як більшість розробників робить, кодять на локалці, а потім виливають зміни у веб?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk 
Ну, наприклад, ти кодиш.
Кожна зміна падає на інтернетний **GitHub** чи локальний **GitLab** (бо ти **push**-иш кожен раз).

Наприклад, я тестую.
Якшо мова йде про перевірку коду, то я стягую репозиторій і читаю шо ти напакував туди.
Якшо мова йде про тестування готового продукту, то ми налаштовуємо **GitHub/GitLab** так, шоб кожен комміт до гілки `develop` автоматично запускав деплой всього коду на наш внутрішній тестовий сервер **staging.startup.com**. Як тільки я кажу шо я протестив і все гаразд, то ми робимо **pull request** з `develop` до `master`, а кожен комміт до останнього буде запускати деплой вже на виробничий сервер **startup.com**. Далі ми дивимось чи все ніштяк, і якшо так, то йдем собі по справах, а як нє — відкатуємо з `master`-а останній комміт і тестуємо краще на цей раз.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir _шоб кожен комміт до гілки develop автоматично запускав деплой всього коду на наш внутрішній тестовий сервер_ 

а можеш дати лінк, будь ласка, де є файній опис цього кроку?

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir бо не дуже зрозуміло як його так налаштувати

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk просто **hook**-и глянь, **"git hooks"**. Суть в тому шо можна виконати будь-яку команду після комміту, наприклад, або до комміту. І до комміту я, наприклад, вішаю команду, яка перевіряє код на лишні пробіли і не дозволяє пушити, а після комміту вішаю команду, яка копіює файли з репозиторію в папку `/var/www`.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir як відправляти гілку мастер на сервер атоматоматично?

**Comment by volodymyr-kushnir** [comment]
В папку **.git/hooks** файл **post-receive** (виконуваний — .bat, .exe, .sh, залежно від системи), в якому список команд, які треба виконати, наприклад
```
cp -r /opt/my-project-name.com/src/* /var/www/
```

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk та просто запхай в свому репозиторії туди **calc.exe**, але перейменуй на **pre-commit.exe**, і потім попробуй закоммітити шось.
https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir перейменував та залив без проблем через гіт шел, чи треба було через локалку?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk є файл **.git/hooks/pre-commit.exe** в твоїй репі локальній? Якшо є, то тепер він  буде запускатись кожен раз коли ти коммітиш. Ну, мав би, принаймні.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir та, я туди його запхав, але як тепер з ним працювати не дуже розумію

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir тобто при коміті будь якого іншого файлу, ехе файл буде виконуватись автоматично шоб там не було? Не дуже розумію як це зв'язати з веб проектом

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk та просто коммітни шось в репозиторій, текст зміни в README.md чи шо, ну і `git commit` і побачиш чи запуститься той твій **pre-commit.exe** чи ні.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir а де видно, що він виконується?

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir  отаке маю у шелі http://joxi.ru/p27o9gMSo51wQ2

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir  сюди помістив той файл http://joxi.ru/MAjpoRYs4aPMZm

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk виявилось, шо на вінді воно трохи не так і все одно використовує **bash**. В общєм, той файл заміни текстовим файлом **pre-commit** без розширення з таким вмістом:
```
#!/bin/sh
/c/Windows/System32/calc.exe
```
І тоді можеш пробувати коммітити.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir запустився калькулятор

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir воно виконало скрипт на локальній машині я так зрозумів, як то перенсти до веб розробки?

**Comment by volodymyr-kushnir** [comment]
@yaroslav-mironyuk easy. Мати точно такий самий скрипт для віддаленого репозиторію. Якшо віддаленим буде твій власний GitLab, то налаштовуєш у ньому, а якшо ти використовуєш GitHub, то — :tada: — GitHub Enterprise і налаштовуєш там.

**Comment by yaroslav-mironyuk** [comment]
@volodymyr-kushnir дякую, буду вивчати
